name: Build Rasel Toolset Installer

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter Pillow PyPDF2 qrcode opencv-python-headless PyMuPDF pyinstaller

    - name: Build Portable EXE
      run: |
        pyinstaller --noconsole --onefile --hidden-import=fitz --hidden-import=cv2 main.py

    - name: Prepare Setup File
      run: |
        copy setup.iss dist\setup.iss

    - name: Compile Inno Setup Installer
      uses: aybe/iscc-action@v2
      with:
        filepath: dist/setup.iss

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Rasel-WebTools-Setup
        path: dist/Rasel_WebTools_Setup.exe
